### PR TITLE
Updates for Jellyfin release 10.10.0

### LINKED ISSUE #24: [BUG] Do not show boutton on movies
On every movies the button is showing, but since it's a movie why showing it?
chrome_oA9CI8g2UG

### LINKED ISSUE #26: Episode summary is cut off if it's longer than the height the video thumbnail takes up
Overflow of the episode summary is cut off when its height would be greater than the height of the video thumbnail. Imo it would look much better if the entire element would change size to accommodate the text of the summary including the margins / padding of the element.

See the video for further explanation, I'm encountering the issue on this screen with the preview of episodes 7, 8 and 9; episode 6 is fine as it has a short summary.

https://github.com/user-attachments/assets/1fabd9b2-0146-430e-844a-93e1b4d168c8

Would've loved to fix this myself, but I'm a bit overwhelmed by all the components being built with typescript as I didn't find any CSS files. Keep up the work, love the plugin and its progress over the last months!

### LINKED ISSUE #38: [Bug] Webos: the preview window didn't close when stopping an episode by going back to library
Environment

Server 10.9.11
Plug-in 1.2.4.0

Reproduction steps

- start an episode
- press episodes preview button
- press "back" button on the remote

It leads you to the previous screen (library/episode details/show details/...) and doesn't close the preview windows.

While this behavior is a bug, it might be fixed by the improvement asked in https://github.com/Namo2/InPlayerEpisodePreview/issues/20

### PR DESCRIPTION
**Pull request by Namo2**
Changes needed for the new Update:
- [x] Handle new API Changes
- [x] Fix Episode Starting

Additional enhancements:
- [x] Improved refreshing of episode details in UI
- [x] Improved CSS (closes #26)
- [x] Hide button for single elements (closes #24)
- [x] Added collection support
- [x] Add other supported rating options
- [x] Fix Popup not closing on "Back" event (closes #38)

### CODE REVIEW

**Comment by Gauvino** [comment]
Hello, is it difficult to fix this problem also for the new release ?

https://github.com/Namo2/InPlayerEpisodePreview/issues/24

**Comment by Namo2** [comment]
> Hello, is it difficult to fix this problem also for the new release ?
> 
> #24

Thanks for reminding me. I will check there are a few days left anyway ^^
Right now it is not happening on my movie library. I guess it depends on the library type you set yourself.
Ofc i understand that sometimes Movies and Shows are mixed together (e.g. many do this for Anime i guess), so i will try to fix it but i will have to check the limitations (or find another hacky work around)

**Comment by Gauvino** [comment]
Maybe you could scrape the TMDb id or something like this to know if it's a movies or a show or something else ?

**Comment by Namo2** [comment]
@Gauvino you asked the last time how to test the current version i am working on, so i will put the dll here this time.
You can just put it in the plugin folder of the current version you have installed. You need to disable autoUpdate in the meta.json i think.
Also you need the current unstable version of Jellyfin.

Keep in mind that it is very untested.
I will work further on it tomorrow.

[Namo.Plugin.InPlayerEpisodePreview.zip](https://github.com/user-attachments/files/17250484/Namo.Plugin.InPlayerEpisodePreview.zip)

**Comment by Namo2** [comment]
And we now have support for collections.
Meaning if you start a Movie collection (e.g. a collection for Iron-Man 1-3)
all 3 movies should appear in the list but it only works if you start one of them from the collections tab/library

**Comment by Gauvino** [comment]
> @Gauvino you asked the last time how to test the current version i am working on, so i will put the dll here this time.
> 
> You can just put it in the plugin folder of the current version you have installed. You need to disable autoUpdate in the meta.json i think.
> 
> Also you need the current unstable version of Jellyfin.
> 
> 
> 
> Keep in mind that it is very untested.
> 
> I will work further on it tomorrow.
> 
> 
> 
> [Namo.Plugin.InPlayerEpisodePreview.zip](https://github.com/user-attachments/files/17250484/Namo.Plugin.InPlayerEpisodePreview.zip)
> 
> 

I don't have any unstable version running and it would take me so much time to deploy one so for now I'll wait for 10.10 release

**Comment by Gauvino** [comment]
This PR doesn't work for 10.9

**Comment by Namo2** [comment]
> This PR doesn't work for 10.9

Sadly not, but the official 10.10.0 release should come out on Saturday Oct. 12th
according to the [roadmap](https://jellyfin.org/posts/release-roadmap-10.10.0/)

I don't know the release time yet but i will try to have an eye on it, so i can quickly push the new update

**Comment by Gauvino** [comment]
> > This PR doesn't work for 10.9
> 
> Sadly not, but the official 10.10.0 release should come out on Saturday Oct. 12th according to the [roadmap](https://jellyfin.org/posts/release-roadmap-10.10.0/)
> 
> I don't know the release time yet but i will try to have an eye on it, so i can quickly push the new update

Thanks you so much for all the work you did!

Did you ever try Sourcery AI on your code?
https://github.com/apps/sourcery-ai/installations/select_target

I've tried it and you can do many improvement with it I think so have a look when you can, I think it would be very cool to optimize be a bit more since it's a big new release!

**Comment by Namo2** [comment]
> > > This PR doesn't work for 10.9
> > 
> > 
> > Sadly not, but the official 10.10.0 release should come out on Saturday Oct. 12th according to the [roadmap](https://jellyfin.org/posts/release-roadmap-10.10.0/)
> > I don't know the release time yet but i will try to have an eye on it, so i can quickly push the new update
> 
> Thanks you so much for all the work you did!
> 
> Did you ever try Sourcery AI on your code? https://github.com/apps/sourcery-ai/installations/select_target
> 
> I've tried it and you can do many improvement with it I think so have a look when you can, I think it would be very cool to optimize be a bit more since it's a big new release!
> 
> You can install it on your IDE, preferably VSCode

Thanks for the idea, maybe I will.
However, i guess the biggest improvement would be to switch to a framework like react.
Currently everything is a bit hacky.

I also have a bit more time in the evenings at the moment, so currently i am considering to have a look at the Jellyfin code itself again and check how difficult it would be to implement this plugin there. 
Would be the best way to increase performance, stability etc.

Also thank you too, always happy to see that someone enjoys my work.

**Comment by Gauvino** [comment]
> > > > This PR doesn't work for 10.9
> > > 
> > > 
> > > Sadly not, but the official 10.10.0 release should come out on Saturday Oct. 12th according to the [roadmap](https://jellyfin.org/posts/release-roadmap-10.10.0/)
> > > I don't know the release time yet but i will try to have an eye on it, so i can quickly push the new update
> > 
> > 
> > Thanks you so much for all the work you did!
> > Did you ever try Sourcery AI on your code? [github.com/apps/sourcery-ai/installations/select_target](https://github.com/apps/sourcery-ai/installations/select_target)
> > I've tried it and you can do many improvement with it I think so have a look when you can, I think it would be very cool to optimize be a bit more since it's a big new release!
> > You can install it on your IDE, preferably VSCode
> 
> Thanks for the idea, maybe I will. However, i guess the biggest improvement would be to switch to a framework like react. Currently everything is a bit hacky.
> 
> I also have a bit more time in the evenings at the moment, so currently i am considering to have a look at the Jellyfin code itself again and check how difficult it would be to implement this plugin there. Would be the best way to increase performance, stability etc.
> 
> Also thank you too, always happy to see that someone enjoys my work.

I really enjoy it, I follow the project from really neat.

React would be a very good idea for now but the best would be to have the plugin implemented for 10.11

**Pull request merged**
