### PR TITLE
V1.2.2.0

### LINKED ISSUE #21: [Bug]: Auto-scroll on bottom episode
I've found a little thing I think, no problematic at all on pc but could by on other device.
When clicking on the bottom media it doesn't auto-scroll to it you have to manually scroll to get to it.
Exemple: 
chrome_TtgrYZHV9H

### LINKED ISSUE #27: [bug] Breaks server discovery
Started to get reports that people can't reach my Jellyfin instance and after some investigating it looks like this server causes the web client to lose track of where the server is. 

When users go to the domain for the instance they are greeted with

```
No servers have been found using the automatic server discovery

[Add server]
```

Users can click the button and type the same base URL as they're visiting in to access the server again but this isn't intuitive or intended behavior. After digging around in my Nginx config and getting nowhere I tried disabling the last plugin I installed (this one) and everything instantly went back to normal.

### PR DESCRIPTION
**Pull request by Namo2**
This PR should fix the following problems:

- [x] Icon color on hover
- [x] Auto scrolling to selected episode (closes #21)
- [x] Server discovery if not logged in (closes #27)
- [x] Security updates

### CODE REVIEW

**Comment by Gauvino** [comment]
You should add a workflow like intro-skipper to build a .dll automatically for easier testing
https://github.com/jumoog/intro-skipper/blob/master/.github/workflows/build.yml

**Comment by Namo2** [comment]
> You should add a workflow like intro-skipper to build a .dll automatically for easier testing https://github.com/jumoog/intro-skipper/blob/master/.github/workflows/build.yml

Ha, I actually tried it after the last release, but I didn't have the time and energy to finish it.
It takes a few minutes to create a new version, but that's fine for now. I'd rather work on the bugs I can finish.

**Comment by Gauvino** [comment]
How can I test the plugin right now ?

**Comment by Namo2** [comment]
> How can I test the plugin right now ?

Give me a minute. There will be a release in a second

**Pull request merged**
